default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS"){5} %>
  username: root
  password: "20011998"
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: fad_development

test:
  <<: *default
  database: fad_test

production:
  <<: *default
  database: fad_production
  username: fad
  password: <%= ENV["FAD_DATABASE_PASSWORD"] %>
