# Numbers in model
smallest:
  of_price: 0
  of_discount: 0
  of_star: 0
  of_quantity: 0
biggest:
  of_discount: 100
  of_star: 6
  of_quantity: 100
size:
  of_email: 255
  of_name: 30
  of_password: 6
  address: 255

# Language
en:
  locale: "en"
vn:
  locale: "vi"

# Checkbox
remembered: "1"
checked: "1"

# Paginate
items: 20

# Limit
tops: 12

# Quantity
max_quantity: 99
truncate: 120
requests: 100
sum_quantity: 100

# limit per_page
limit:
  five: 5
  ten: 10
  fifteen: 15
  twenty: 20
  thirty: 30
  fourty: 40
  fifty: 50
